
version: '3'
services:
  site:
    container_name: webnixly
    command: jekyll serve
    image: jekyll/jekyll:3.8.6
    # environment:
    #   JEKYLL_UID: 1001
    #   JEKYLL_GID: 1001
    volumes:
      -  .:/srv/jekyll:Z
    ports:
      - 4000:4000
